In [ ]:
# Cleaning and formatting the raw data for the Groceries Survey
# Authors - Ojas, Avi, Nancy, Julie, Abdul, Minsoo
# As of Nov 29th

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import seaborn as sb
import numpy as np

In [3]:
path = './ba222Project_RawData_GroceryShopping_11.29.22.csv.csv'
GroceriesData = pd.read_csv(path)
GroceriesData

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q8_6,Q8_7,Q8_8,Q9,Q10,Q11,Q12,Q13,Q14,Q15
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,What do you prioritize most when selecting a p...,What do you prioritize most when selecting a p...,What do you prioritize most when selecting a p...,What categories of food do you spend the most ...,What best describes your employment status?,What role do you play when buying groceries fo...,"What is your age? (In years, example : 21)",What is your gender?,Under what range does your average yearly hous...,How many household members do you shop for?
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID22_4""}","{""ImportId"":""QID22_5""}","{""ImportId"":""QID22_6""}","{""ImportId"":""QID23""}","{""ImportId"":""QID26""}","{""ImportId"":""QID28""}","{""ImportId"":""QID4_TEXT""}","{""ImportId"":""QID14""}","{""ImportId"":""QID2""}","{""ImportId"":""QID15_TEXT""}"
2,2022-11-10 18:06:08,2022-11-10 18:08:38,Survey Preview,NaN,100,150,True,2022-11-10 18:08:39,R_2ctuXEq3xuMohXa,NaN,...,3,5,6,Dairy Products,Employed Full Time,Not involved in making decisions,22,Male,$0 - $25K,3
3,2022-11-19 12:21:54,2022-11-19 12:23:50,IP Address,128.197.29.250,100,116,True,2022-11-19 12:23:50,R_1gShS8iJRMmWoXg,NaN,...,5,2,3,Frozen Food,Employed Full Time,I make the decisions,21,Male,$75K - $100K,2
4,2022-11-19 12:38:53,2022-11-19 12:40:44,IP Address,107.115.17.18,100,110,True,2022-11-19 12:40:44,R_3qUra1MzvLknOY3,NaN,...,4,3,5,Fresh Produce,Student,I make the decisions,22,Male,$25k - $50k,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,2022-11-28 19:39:25,2022-11-28 19:41:14,IP Address,128.197.29.229,100,109,True,2022-11-28 19:41:15,R_3lxADIoZ4FheoiZ,NaN,...,6,3,2,Beverages,Student,I make the decisions,22,Female,$0 - $25K,0
90,2022-11-28 19:38:29,2022-11-28 19:41:39,IP Address,128.197.29.250,100,189,True,2022-11-28 19:41:39,R_3ffOxWTsgIvekGy,NaN,...,4,1,6,Fresh Produce,Student,I make the decisions,28,Male,150K+,1
91,2022-11-28 19:37:11,2022-11-28 19:43:40,IP Address,174.242.77.74,100,388,True,2022-11-28 19:43:40,R_pE2D1HIwwIbSiA1,NaN,...,2,3,4,Fresh Produce,Student,I make the decisions,21,Male,$25k - $50k,1
92,2022-11-28 19:41:46,2022-11-28 19:44:24,IP Address,172.58.216.90,100,157,True,2022-11-28 19:44:24,R_2ePBkFKT50KJm1H,NaN,...,5,2,4,Snacks,Student,I make the decisions,21,Male,$100K - $125K,"I’m not beta, 3"
93,2022-11-28 19:39:35,2022-11-28 19:44:43,IP Address,128.197.29.254,100,308,True,2022-11-28 19:44:43,R_yxsz9gCciEImOpr,NaN,...,3,1,2,Beverages,Employed Part Time,I make the decisions,21,Male,$0 - $25K,1

In [4]:
# First Cleaning Pass:
colHeaders = GroceriesData.iloc [0]

In [5]:
cleanData = GroceriesData.drop([0,1])

In [6]:
cleanData = cleanData [(cleanData.DistributionChannel == 'qr') | (cleanData.DistributionChannel == 'email')]

In [7]:
cleanData = cleanData[~(cleanData.IPAddress.duplicated())]

In [8]:
cleanData = cleanData[cleanData.Finished == 'True']

In [9]:
cleanDatacleanData.columns

Index(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5_1',
       'Q5_2', 'Q5_3', 'Q5_4', 'Q5_5', 'Q5_6', 'Q5_7', 'Q6', 'Q7_1', 'Q7_2',
       'Q8_4', 'Q8_9', 'Q8_5', 'Q8_6', 'Q8_7', 'Q8_8', 'Q9', 'Q10', 'Q11',
       'Q12', 'Q13', 'Q14', 'Q15'],
      dtype='object')

In [10]:
# Second Cleaning Pass:
cleanData.iloc[0]

StartDate                 2022-11-19 12:21:54
EndDate                   2022-11-19 12:23:50
Status                             IP Address
IPAddress                      128.197.29.250
Progress                                  100
Duration (in seconds)                     116
Finished                                 True
RecordedDate              2022-11-19 12:23:50
ResponseId                  R_1gShS8iJRMmWoXg
RecipientLastName                         NaN
RecipientFirstName                        NaN
RecipientEmail                            NaN
ExternalReference                         NaN
LocationLatitude                      42.3464
LocationLongitude                    -71.0975
DistributionChannel                        qr
UserLanguage                               EN
Q1                                         50
Q2                                          1
Q3                                    10 - 20
Q4                                  $60 - $89
Q5_1                                 Distance
Q5_2                        Grocery Selection
Q5_3                                        0
Q5_4                                    Price
Q5_5                                        0
Q5_6                                        0
Q5_7                                    Deals
Q6                                        Yes
Q7_1                                        4
Q7_2                                        5
Q8_4                                        4
Q8_9                                        6
Q8_5                                        1
Q8_6                                        5
Q8_7                                        2
Q8_8                                        3
Q9                                Frozen Food
Q10                        Employed Full Time
Q11                      I make the decisions
Q12                                        21
Q13                                      Male
Q14                              $75K - $100K
Q15                                         2
Name: 3, dtype: object

In [23]:
Q15 = cleanData.Q15

cleanData=cleanData.dropna(subset=['Q15'])
print(Q15.unique())

['2' '1' '1 (self)' '4' '0' '3-4' 'me' '6' '3']

In [ ]:
Q1 = cleanData.Q1
Q1Float = Q1.astype('float')
cleanData ['Q1Float'] = Q1Float

In [ ]:
Q2 = cleanData.Q2
Q2Float = Q2.astype('float')
cleanData ['Q2Float'] = Q2Float

In [ ]:
Q3 = cleanData.Q3
Q3clean = Q3.str.replace('Less than', '>')
cleanData ['Q3clean'] = Q3clean

In [ ]:
Q4 = cleanData.Q4
Q4clean = Q4.str.replace('$','')
Q4clean = Q4.str.replace('+','<')
cleanData ['Q4clean'] = Q4clean

In [ ]:
Q12 = cleanData.Q12
Q12Float = Q12.astype('float')
cleanData ['Q12Float'] = Q12Float

In [ ]:
Q14 = cleanData.Q14
Q14clean = Q14.str.replace('$','')
Q14clean = Q14.str.replace('+','<')
cleanData ['Q14clean'] = Q14clean

In [ ]:
cleanData.columns

In [ ]:
Q15 = cleanData["Q15"] 
Q15Float = Q15.astype('float')
cleanData ['Q15Float'] = Q15Float

In [ ]:
cleanData = cleanData.drop(columns =
['StartDate', 'EndDate', 'Status', 'IPAddress',
'Progress','Duration (in seconds)', 'Finished',
'RecordedDate', 'ResponseId', 'RecipientLastName',
'RecipientFirstName', 'RecipientEmail', 'ExternalReference',
'LocationLatitude', 'LocationLongitude',
'DistributionChannel', 'UserLanguage'], axis = 1)

In [ ]:
cleanData = cleanData.drop(columns = ['Q1', 'Q2', 'Q3', 'Q4', 'Q12', 'Q14', 'Q15'], axis = 1)

In [ ]:
cleanData[cleanData.Q5_1 == -99] = np.nan
cleanData[cleanData.Q5_2 == -99] = np.nan
cleanData[cleanData.Q5_3 == -99] = np.nan
cleanData[cleanData.Q5_4 == -99] = np.nan
cleanData[cleanData.Q5_5 == -99] = np.nan
cleanData[cleanData.Q5_6 == -99] = np.nan
cleanData[cleanData.Q5_7 == -99] = np.nan
cleanData[cleanData.Q6 == -99] = np.nan
cleanData[cleanData.Q7_1 == -99] = np.nan
cleanData[cleanData.Q7_2 == -99] = np.nan
cleanData[cleanData.Q8_4 == -99] = np.nan
cleanData[cleanData.Q8_5 == -99] = np.nan
cleanData[cleanData.Q8_6 == -99] = np.nan
cleanData[cleanData.Q8_7 == -99] = np.nan
cleanData[cleanData.Q8_8 == -99] = np.nan
cleanData[cleanData.Q8_9 == -99] = np.nan
cleanData[cleanData.Q9 == -99] = np.nan
cleanData[cleanData.Q10 == -99] = np.nan
cleanData[cleanData.Q11 == -99] = np.nan
cleanData[cleanData.Q13 == -99] = np.nan
cleanData[cleanData.Q1Float == -99] = np.nan
cleanData[cleanData.Q2Float == -99] = np.nan
cleanData[cleanData.Q3clean == -99] = np.nan
cleanData[cleanData.Q4clean == -99] = np.nan
cleanData[cleanData.Q12Float == -99] = np.nan
cleanData[cleanData.Q14clean == -99] = np.nan
cleanData[cleanData.Q15Float == -99] = np.nan

In [ ]:
cleanData.columns

In [ ]:
Weekly_Expenditure = cleanData.Q1Float
cleanData ['Weekly_Expenditure'] = Weekly_Expenditure

Weekly_Shopping = cleanData.Q2Float
cleanData ['Weekly_Shopping'] = Weekly_Shopping

Destination_Time = cleanData.Q3clean
cleanData ['Destination_Time'] = Destination_Time

Spending_Eating = cleanData.Q4clean
cleanData ['Spending_Eating'] = Spending_Eating

reason_Distance = cleanData.Q5_1
cleanData ['reason_Distance'] = reason_Distance

reason_Grocery_Selection = cleanData.Q5_2
cleanData ['reason_Grocery_Selection'] = reason_Grocery_Selection

reason_Customer_Service = cleanData.Q5_3
cleanData ['reason_Customer_Service'] = reason_Customer_Service

reason_Price = cleanData.Q5_4
cleanData ['reason_Price'] = reason_Price

reason_Parking = cleanData.Q5_5
cleanData ['reason_Parking'] = reason_Parking

reason_Online_Shopping = cleanData.Q5_6
cleanData ['reason_Online_Shopping'] = reason_Online_Shopping

reason_Deals = cleanData.Q5_7
cleanData ['reason_Deals'] = reason_Deals

Multiple_Shoppers = cleanData.Q6
cleanData ['Multiple_Shoppers'] = Multiple_Shoppers

Is_Online_Accessible = cleanData.Q7_1
cleanData ['Is_Online_Accessible'] = Is_Online_Accessible

More_Online_Accessible = cleanData.Q7_2
cleanData ['More_Online_Accessible'] = More_Online_Accessible

Priority_Price = cleanData.Q8_4
cleanData ['Priority_Price'] = Priority_Price

Priority_Service = cleanData.Q8_5
cleanData ['Priority_Service'] = Priority_Service

Priority_QOP = cleanData.Q8_6
cleanData ['Priority_QOP'] = Priority_QOP

Priority_Health = cleanData.Q8_7
cleanData ['Priority_Health'] = Priority_Health

Priority_Convenience = cleanData.Q8_8
cleanData ['Priority_Convenience'] = Priority_Convenience

Priority_Variety = cleanData.Q8_9
cleanData ['Priority_Variety'] = Priority_Variety

Category_Food = cleanData.Q9
cleanData ['Category_Food'] = Category_Food

Employment = cleanData.Q10
cleanData ['Employment'] = Employment

Buying_Role = cleanData.Q11
cleanData ['Buying_Role'] = Buying_Role

Age = cleanData.Q12Float
cleanData ['Age'] = Age

Gender = cleanData.Q13
cleanData ['Gender'] = Gender

Average_Income = cleanData.Q14clean
cleanData ['Average_Income'] = Average_Income

Household_Members = cleanData.Q15Float
cleanData ['Household_Members'] = Household_Members

cleanData = cleanData.drop(columns = ['Q5_1', 'Q5_2', 'Q5_3', 'Q5_4', 'Q5_5', 'Q5_6', 'Q5_7', 'Q6', 'Q7_1', 'Q7_2', 'Q8_4', 'Q8_9', 'Q8_5', 'Q8_6', 'Q8_7', 'Q8_8', 'Q9', 'Q10','Q11', 'Q13', 'Q1Float', 'Q2Float', 'Q3clean', 'Q4clean', 'Q12Float', 'Q14clean', 'Q15Float'], axis = 1)

In [ ]:
cleanData